# globals:
#  namespace: "namespace"
#  namePrefix: "namePrefix"
#  nameSuffix: "nameSuffix"
#  nameReleasePrefix: "nameReleasePrefix"
#  labels:
#    key: "label"
#  annotations:
#    key: "annotation"
#  images:
#    - image: "old-image"
#      newName: "new-image"
#      newTag: "new-tag"
#      digest: "digest"
#      pullSecrets:
#        - name: "pull-secret"
#  resources:
#    - name: "resource"
#      version: "v1"
#      kind: "Resource"
overlay: on-prem
DATABASE_URL: postgres://postgres@postgres-postgresql:5432/postgres?sslmode=disable
POSTGRES_HOST_AUTH_METHOD: trust
PORT: "3000"
DEBUG_QUERIES: "true"
ON_PREM: "true"
AUTH_SECRET: Kd73PfXo5sL1YqZrT0e9dVbU8qWn4cMaH2jRuLtX3kE=
CONNECT_URL: https://mcp-s-connect.mcp-s.com
AUTO_AUTHENTICATE_TOKEN: Yp49XtVm7qN2RbLsG8cKeZwT5oDh1uMiA3vJfQxL6sE=
RATE_LIMIT_MAX: "1000"
RATE_LIMIT_WINDOW: "60000"
ENCRYPTION_KEY: iL7wUJhqRMPFY0asXqLAn1JjW9kv0OqC4NHtqKHt5VY=
