{{- /*
This file was autogenerated by helmify-kustomize
DO NOT EDIT: Any changes will be overwritten
*/ -}}
{{- define "hlmfk-1-2-575485958e.valuesYaml" -}}
{{- $runtime_deployment_name := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "deploymentName") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $runtime_autoscaling_targetMemory := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "autoscaling" "targetMemoryUtilizationPercentage") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $runtime_autoscaling_targetCPU := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "autoscaling" "targetCPUUtilizationPercentage") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $runtime_autoscaling_maxReplicas := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "autoscaling" "maxReplicas") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $runtime_autoscaling_minReplicas := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "autoscaling" "minReplicas") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $runtime_podResources := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "podResources") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $runtime_registry := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "registry") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $runtime_nodeSelector := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "nodeSelector") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $runtime_podLabels := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "podLabels") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $runtime_podAnnotations := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "podAnnotations") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $runtime_secret_name := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "secretName") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $runtime_app_tag := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "appVersion") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $runtime_replicas := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "replicas") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $runtime_namespace := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "namespace") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $anchor_namespace_default := printf `` -}}
{{- $anchor_replicas_default := printf `1` -}}
{{- $anchor_app_tag_default := printf `latest` -}}
{{- $anchor_secret_name_default := printf `mcp-s-run-container-secret-vars` -}}
{{- $anchor_podAnnotations_default := printf `` -}}
{{- $anchor_podLabels_default := printf `app: mcp-s-run` -}}
{{- $anchor_nodeSelector_default := printf `` -}}
{{- $anchor_registry_default := printf `quay.io/webrix/mcp-s-run` -}}
{{- $anchor_podResources_default := printf `requests:
  cpu: 100m
    memory: 200Mi
limits:
  cpu: 1000m
    memory: 2048Mi` -}}
{{- $anchor_autoscaling_minReplicas_default := printf `1` -}}
{{- $anchor_autoscaling_maxReplicas_default := printf `3` -}}
{{- $anchor_autoscaling_targetCPU_default := printf `70` -}}
{{- $anchor_autoscaling_targetMemory_default := printf `80` -}}
{{- $anchor_deployment_name_default := printf `mcp-s-run` -}}
{{- $final_namespace := "" -}}
{{- if eq $runtime_namespace "__HELMIFY_NOT_FOUND__" -}}
{{- $final_namespace = $anchor_namespace_default -}}
{{- else -}}
{{- $final_namespace = $runtime_namespace -}}
{{- end -}}
{{- $final_replicas := "" -}}
{{- if eq $runtime_replicas "__HELMIFY_NOT_FOUND__" -}}
{{- $final_replicas = $anchor_replicas_default -}}
{{- else -}}
{{- $final_replicas = $runtime_replicas -}}
{{- end -}}
{{- $final_app_tag := "" -}}
{{- if eq $runtime_app_tag "__HELMIFY_NOT_FOUND__" -}}
{{- $final_app_tag = $anchor_app_tag_default -}}
{{- else -}}
{{- $final_app_tag = $runtime_app_tag -}}
{{- end -}}
{{- $final_secret_name := "" -}}
{{- if eq $runtime_secret_name "__HELMIFY_NOT_FOUND__" -}}
{{- $final_secret_name = $anchor_secret_name_default -}}
{{- else -}}
{{- $final_secret_name = $runtime_secret_name -}}
{{- end -}}
{{- $final_podAnnotations := "" -}}
{{- if eq $runtime_podAnnotations "__HELMIFY_NOT_FOUND__" -}}
{{- $final_podAnnotations = $anchor_podAnnotations_default -}}
{{- else -}}
{{- $final_podAnnotations = $runtime_podAnnotations -}}
{{- end -}}
{{- $final_podLabels := "" -}}
{{- if eq $runtime_podLabels "__HELMIFY_NOT_FOUND__" -}}
{{- $final_podLabels = $anchor_podLabels_default -}}
{{- else -}}
{{- $final_podLabels = $runtime_podLabels -}}
{{- end -}}
{{- $final_nodeSelector := "" -}}
{{- if eq $runtime_nodeSelector "__HELMIFY_NOT_FOUND__" -}}
{{- $final_nodeSelector = $anchor_nodeSelector_default -}}
{{- else -}}
{{- $final_nodeSelector = $runtime_nodeSelector -}}
{{- end -}}
{{- $final_registry := "" -}}
{{- if eq $runtime_registry "__HELMIFY_NOT_FOUND__" -}}
{{- $final_registry = $anchor_registry_default -}}
{{- else -}}
{{- $final_registry = $runtime_registry -}}
{{- end -}}
{{- $final_podResources := "" -}}
{{- if eq $runtime_podResources "__HELMIFY_NOT_FOUND__" -}}
{{- $final_podResources = $anchor_podResources_default -}}
{{- else -}}
{{- $final_podResources = $runtime_podResources -}}
{{- end -}}
{{- $final_autoscaling_minReplicas := "" -}}
{{- if eq $runtime_autoscaling_minReplicas "__HELMIFY_NOT_FOUND__" -}}
{{- $final_autoscaling_minReplicas = $anchor_autoscaling_minReplicas_default -}}
{{- else -}}
{{- $final_autoscaling_minReplicas = $runtime_autoscaling_minReplicas -}}
{{- end -}}
{{- $final_deployment_name := "" -}}
{{- if eq $runtime_deployment_name "__HELMIFY_NOT_FOUND__" -}}
{{- $final_deployment_name = $anchor_deployment_name_default -}}
{{- else -}}
{{- $final_deployment_name = $runtime_deployment_name -}}
{{- end -}}
{{- $final_autoscaling_maxReplicas := "" -}}
{{- if eq $runtime_autoscaling_maxReplicas "__HELMIFY_NOT_FOUND__" -}}
{{- $final_autoscaling_maxReplicas = $anchor_autoscaling_maxReplicas_default -}}
{{- else -}}
{{- $final_autoscaling_maxReplicas = $runtime_autoscaling_maxReplicas -}}
{{- end -}}
{{- $final_autoscaling_targetCPU := "" -}}
{{- if eq $runtime_autoscaling_targetCPU "__HELMIFY_NOT_FOUND__" -}}
{{- $final_autoscaling_targetCPU = $anchor_autoscaling_targetCPU_default -}}
{{- else -}}
{{- $final_autoscaling_targetCPU = $runtime_autoscaling_targetCPU -}}
{{- end -}}
{{- $final_autoscaling_targetMemory := "" -}}
{{- if eq $runtime_autoscaling_targetMemory "__HELMIFY_NOT_FOUND__" -}}
{{- $final_autoscaling_targetMemory = $anchor_autoscaling_targetMemory_default -}}
{{- else -}}
{{- $final_autoscaling_targetMemory = $runtime_autoscaling_targetMemory -}}
{{- end -}}
# globals:
#  namespace: "namespace"
#  namePrefix: "namePrefix"
#  nameSuffix: "nameSuffix"
#  nameReleasePrefix: "nameReleasePrefix"
#  labels:
#    key: "label"
#  annotations:
#    key: "annotation"
#  images:
#    - image: "old-image"
#      newName: "new-image"
#      newTag: "new-tag"
#      digest: "digest"
#      pullSecrets:
#        - name: "pull-secret"
#  resources:
#    - name: "resource"
#      version: "v1"
#      kind: "Resource"
overlay: "overlays/on-prem"
namespace: &namespace {{ $final_namespace }}
replicas: &replicas {{ $final_replicas }}
appVersion: &app_tag {{ $final_app_tag }}
secretName: &secret_name {{ $final_secret_name }}
podAnnotations: &podAnnotations 
{{ $final_podAnnotations | indent 2 }}
podLabels: &podLabels 
{{ $final_podLabels | indent 2 }}
nodeSelector: &nodeSelector 
{{ $final_nodeSelector | indent 2 }}
registry: &registry {{ $final_registry }}
podResources: &podResources 
{{ $final_podResources | indent 2 }}
autoscaling:
  enabled: false
  minReplicas: &autoscaling_minReplicas {{ $final_autoscaling_minReplicas }}
deploymentName: &deployment_name {{ $final_deployment_name }}
globals:
  addStandardHeaders: false
  images:
    - image: quay.io/webrix/mcp-s-run
      newTag: {{ $final_app_tag }}
      newName: {{ $final_registry }}
  namespace: {{ $final_namespace }}
  patches:
    - target:
        kind: Deployment
        name: mcp-s-run
      ops:
        - op: add
          path: /spec/replicas
          value: {{ $final_replicas }}
        - op: add
          path: /spec/template/spec/containers/0/envFrom/1/secretRef/name
          value: {{ $final_secret_name }}
        - op: add
          path: /spec/template/metadata/annotations
          value: {{ $final_podAnnotations | fromYaml | toYaml | nindent 12 }}
        - op: add
          path: /spec/template/metadata/labels
          value: {{ $final_podLabels | fromYaml | toYaml | nindent 12 }}
        - op: add
          path: /spec/template/spec/nodeSelector
          value: {{ $final_nodeSelector | fromYaml | toYaml | nindent 12 }}
        - op: add
          path: /spec/template/spec/containers/0/resources
          value: {{ $final_podResources | fromYaml | toYaml | nindent 12 }}
    - target:
        kind: HorizontalPodAutoscaler
        name: mcp-s-run-hpa
      ops:
        - op: replace
          path: /spec/scaleTargetRef/name
          value: {{ $final_deployment_name }}
        - op: replace
          path: /spec/minReplicas
          value: {{ $final_autoscaling_minReplicas }}
        - op: replace
          path: /spec/maxReplicas
          value: {{ $final_autoscaling_maxReplicas }}
        - op: replace
          path: /spec/metrics/0/resource/target/averageUtilization
          value: {{ $final_autoscaling_targetCPU }}
        - op: replace
          path: /spec/metrics/1/resource/target/averageUtilization
          value: {{ $final_autoscaling_targetMemory }}
manifests:
  - apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: mcp-s-run-hpa
      annotations:
        helmify-kustomize.io/enabled-by: "autoscaling.enabled"
    spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: placeholder
      minReplicas: 1
      maxReplicas: 1
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 1
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 1
env:
  DB_SERVICE_URL: http://mcp-s-db-service
  PORT: "3000"
  AUTH_SECRET: ZI39UlR2sN6HFZauuze0iNEZnNkF1wiOuGklm3bC8dk=
  BASE_URL: https://run.mcp-s.com
  CONNECT_URL: https://connect.mcp-s.com
  LOG_LEVEL: info
  ORG: on-prem-org

{{- end -}}