
{{- $all := fromYaml (include "frmvgglpjj.yamls" (dict "Values" .Values) ) }}
{{- $kustomizeFiles := fromYaml (include "frmvgglpjj.kustomizeFiles" (dict "Values" .Values) ) }}

{{- if .Values.manifests }}
{{- range $key, $manifest := .Values.manifests }}
{{- $result := append $all.manifests (dict "spec" $manifest) }}
{{- $n := set $all "manifests" $result -}}
{{- end }}
{{- end }}

{{- range $key, $manifest := $all.manifests }}
{{- include "ensureMetadata" (dict "manifest" $manifest)}}
{{- if $.Values.images }}
  {{- include "updataImages" (dict "manifest" $manifest "images" $.Values.images)}}
{{- end}}
{{- if $.Values.globals }}
{{- include "setNamespace" (dict "manifest" $manifest "globals" $.Values.globals)}}
{{- include "setNamePrefix" (dict "manifest" $manifest "globals" $.Values.globals)}}
{{- include "setNameSuffix" (dict "manifest" $manifest "globals" $.Values.globals)}}
{{- include "nameReleasePrefix" (dict "manifest" $manifest "globals" $.Values.globals "Values" $.Values)}}
{{- include "labels" (dict "manifest" $manifest "globals" $.Values.globals)}}
{{- include "annotations" (dict "manifest" $manifest "globals" $.Values.globals)}}
{{- end}}
{{- end }}

{{- if and .Values.kustomizeFiles .Values.kustomizeFiles.include }}
{{- if .Values.kustomizeFiles.printNames}}
{{- $kustomizeManifests := fromYaml (include "filterManifests" (dict "manifests" $kustomizeFiles.manifests "Values" $.Values))}}
{{- include "printManifests"  $kustomizeManifests }}
{{- else }}
{{- include "printManifests" $kustomizeFiles}}
{{- end }}
{{- end }}

{{- if .Values.resources }}
{{- range $key, $manifest := .Values.resources }}
{{- $result := append $all.manifests (dict "spec" $manifest) }}
{{- $n := set $all "manifests" $result -}}
{{- end }}
{{- end }}

{{- include "printManifests" $all}}
        