{{- $all := fromYaml (include "hlmfk-0-0-c63698914e.yamls" (dict "Values" .Values) ) }}
{{- $kustomizeFiles := fromYaml (include "hlmfk-0-0-c63698914e.kustomizeFiles" (dict "Values" .Values) ) }}

{{- if .Values.manifests }}
{{- range $key, $manifest := .Values.manifests }}
{{- $result := append $all.manifests (dict "spec" $manifest) }}
{{- $n := set $all "manifests" $result -}}
{{- end }}
{{- end }}

{{- range $key, $manifest := $all.manifests }}
{{- include "hlmfk-0-0.ensureMetadata" (dict "manifest" $manifest)}}
{{- if $.Values.images }}
  {{- include "hlmfk-0-0.updataImages" (dict "manifest" $manifest "images" $.Values.images)}}
{{- end}}
{{- if $.Values.globals }}
{{- include "hlmfk-0-0.setNamespace" (dict "manifest" $manifest "globals" $.Values.globals)}}
{{- include "hlmfk-0-0.setNamePrefix" (dict "manifest" $manifest "globals" $.Values.globals)}}
{{- include "hlmfk-0-0.setNameSuffix" (dict "manifest" $manifest "globals" $.Values.globals)}}
{{- include "hlmfk-0-0.nameReleasePrefix" (dict "manifest" $manifest "globals" $.Values.globals "Values" $.Values)}}
{{- include "hlmfk-0-0.labels" (dict "manifest" $manifest "globals" $.Values.globals)}}
{{- include "hlmfk-0-0.annotations" (dict "manifest" $manifest "globals" $.Values.globals)}}
{{- end}}
{{- end }}

{{- if and .Values.kustomizeFiles .Values.kustomizeFiles.include }}
{{- if .Values.kustomizeFiles.printNames}}
{{- $kustomizeManifests := fromYaml (include "hlmfk-0-0.filterManifests" (dict "manifests" $kustomizeFiles.manifests "Values" $.Values))}}
{{- include "hlmfk-0-0.printManifests"  $kustomizeManifests }}
{{- else }}
{{- include "hlmfk-0-0.printManifests" $kustomizeFiles }}
{{- end }}
{{- end }}

{{- if .Values.resources }}
{{- range $key, $manifest := .Values.resources }}
{{- $result := append $all.manifests (dict "spec" $manifest) }}
{{- $n := set $all "manifests" $result -}}
{{- end }}
{{- end }}

{{- include "hlmfk-0-0.printManifests" $all }}
        