host: example.com
db_base_url: &db_base_url http://mcp-s-db-service
nextauth_url: &nextauth_url https://mcp-s-connect.mcp-s.com
namespace: &namespace webrix-mcp-s



connect:
  globals:
    namespace: *namespace
  enabled: true
  env:
    DB_BASE_URL: *db_base_url
    NEXTAUTH_URL: *nextauth_url
  ingress:
    name: connect
    enabled: true
    namespace: *namespace
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: "" # leave empty to use the host from the values.yaml
        subdomain: connect.
        backend: mcp-s-connect
        paths:
          - path: /
            pathType: Prefix        
app:
  globals:
    namespace: *namespace
  enabled: true
  env:
    DB_BASE_URL: *db_base_url
    NEXTAUTH_URL: *nextauth_url
  ingress:
    name: app
    enabled: true
    namespace: *namespace
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: "" # leave empty to use the host from the values.yaml
        subdomain: app.
        backend: mcp-s-app
        paths:
          - path: /
            pathType: Prefix

run:
  globals:
    namespace: *namespace
  enabled: true
  env:
    DB_BASE_URL: *db_base_url
    NEXTAUTH_URL: *nextauth_url
  ingress:
    name: run
    enabled: true
    namespace: *namespace
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: "" # leave empty to use the host from the values.yaml
        subdomain: run.
        backend: mcp-s-run
        paths:
          - path: /

dbservice:
  globals:
    namespace: *namespace
  enabled: true
  env:
    DB_BASE_URL: *db_base_url
    NEXTAUTH_URL: *nextauth_url