# To control the output of the manifests, you can use the following properties in the globals section:
# FYI helm chart has the concept globals but it's with the property name "global" and not "globals"
# globals:
#  addStandardHeaders: false # by default it's true, `true` will add the standard helm headers to the manifests
#  namespace: "namespace"
#  namePrefix: "namePrefix"
#  nameSuffix: "nameSuffix"
#  nameReleasePrefix: "nameReleasePrefix"
#  labels:
#    key: "label"
#  annotations:
#    key: "annotation"
#  images:
#    - image: "old-image"
#      newName: "new-image"
#      newTag: "new-tag"
#      digest: "digest"
#      pullSecrets:
#        - name: "pull-secret"
#  resources:
#    - name: "resource"
#      version: "v1"
#      kind: "Resource"
overlay: overlays/on-prem
env:
  GRAFANA_URL: http://localhost:3000
  GRAFANA_API_KEY: ""
