# To control the output of the manifests, you can use the following properties in the globals section:
# FYI helm chart has the concept globals but it's with the property name "global" and not "globals"
# helmifyPrefix: "globals"
# globals:
#  addStandardHeaders: false # by default it's true, `true` will add the standard helm headers to the manifests
#  namespace: "namespace"
#  namePrefix: "namePrefix"
#  nameSuffix: "nameSuffix"
#  nameReleasePrefix: "nameReleasePrefix"
#  labels:
#    key: "label"
#  annotations:
#    key: "annotation"
#  resources:
#    - name: "resource"
#      version: "v1"
#      kind: "Resource"
#   images:
#    - image: "old-image"
#      newName: "new-image"
#      newTag: "new-tag"
#      digest: "digest"
#      pullSecrets:
#       - name: "pull-secret"
#  patches:
#    - target:
#      group: "apps"
#      version: "v1"
#      kind: "Deployment"
#      name: "nginx-deployment"
#    ops:
#      - op: "add"
#        path: "/spec/template/spec/containers/0/env/-"
#        value:
#          name: "LOG_LEVEL"
#          value: "debug"
overlay: overlays/on-prem
env:
  AUTH_SECRET: aUi2V5iCVqUrbrdjKty1zH4HCqszXArV9BLVU2giqhY=
  DB_AUTH_SECRET: ZI39UlR2sN6HFZauuze0iNEZnNkF1wiOuGklm3bC8dk=
  DB_BASE_URL: http://mcp-s-db-service
  NEXTAUTH_URL: https://connect2.mcp-s.com
  PORT: "3000"
  AUTO_AUTHENTICATE_TOKEN: balQgAqCpKW979XoibTYSbfCjvj7uSJK+90m0iQG5
  RUN_URL: https://run2.mcp-s.com
  ON_PREM: "true"
  ORG: on-prem-org
  DEBUG: "true"
namespace: mcp-s
replicas: 1
applicationVersion: latest
globals:
  addStandardHeaders: false
  images:
    - image: quay.io/idan-chetrit/mcp-s-connect
      newTag: latest
  namespace: mcp-s
  replicas: 1
  patches:
    - target:
        kind: Deployment
        name: mcp-s-connect
      ops:
        - op: add
          path: /spec/replicas
          value: 1
