name: Release Charts

on:
    # push:
    #   branches:
    #     - main
    #   paths:
    #     - 'chart/**'
    workflow_dispatch:  
    
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      OVERLAY_TO_PUBLISH: on-prem
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: helm-charts
          fetch-depth: 0
      
      - name: Configure Git
        working-directory: helm-charts
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    
      - name: Set up GitHub auth token
        id: github-auth-token
        uses: ./helm-charts/.github/actions/github-auth-token
        with:
          GHA_PAT: ${{ secrets.GHA_PAT }}
          GH_APP_PK: ${{ secrets.GH_APP_PK }}
          GH_APP_ID: ${{ secrets.GH_APP_ID }}

      - name: Checkout deployment
        uses: actions/checkout@v4
        with:
          path: deployment
          repository: webrix-ai/deployment
          fetch-depth: 0
          token: ${{ steps.github-auth-token.outputs.token }}

      - name: Create charts from services
        working-directory: ./helm-charts
        run: |
          npx helmify-kustomize build ../deployment/mcp-s-app/deploy --target ./charts/mcp-s-app --overlay-filter overlays/${{ env.OVERLAY_TO_PUBLISH }} --parametrize =base/container.env --parametrize =overlays/${{ env.OVERLAY_TO_PUBLISH }}/container.env
          npx helmify-kustomize build ../deployment/mcp-s-connect/deploy --target ./charts/mcp-s-connect --overlay-filter overlays/${{ env.OVERLAY_TO_PUBLISH }} --parametrize =base/container.env --parametrize =overlays/${{ env.OVERLAY_TO_PUBLISH }}/container.env
          npx helmify-kustomize build ../deployment/mcp-s-db-service/deploy --target ./charts/mcp-s-db-service --overlay-filter overlays/${{ env.OVERLAY_TO_PUBLISH }} --parametrize =base/container.env --parametrize =overlays/${{ env.OVERLAY_TO_PUBLISH }}/container.env
          npx helmify-kustomize build ../deployment/mcp-s-run/deploy --target ./charts/mcp-s-run --overlay-filter overlays/${{ env.OVERLAY_TO_PUBLISH }} --parametrize =base/container.env --parametrize =overlays/${{ env.OVERLAY_TO_PUBLISH }}/container.env
      
      - name: add to git
        working-directory: helm-charts
        run: |
          git add .
          if ! git diff-index --quiet HEAD --; then
            git commit -m "updated charts"
            git push
          else
            echo "No changes to commit, working tree is clean"
          fi

      # Move helm-charts to root
      - name: Move helm-charts repo to root
        run: |
          mv ./helm-charts /tmp/helm-charts
          rm -rf ./helm-charts
          rm -rf ./deployment
          mv /tmp/helm-charts .

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        # with:
        #   charts_dir: ./charts